using UnityEngine;
using MoonSharp.Interpreter;
using System;
using System.Collections.Generic;
using System.Reflection;
using System.IO;

public class LuaTest : MonoBehaviour
{
    Script luaScript = new Script();
    DynValue luaUpdateFunction;
    public string pathToLuaDirectory;

    void Start()
    {
        // Register functions. 
        luaScript.Globals["print"] = (Action<string>)LuaPrint;
        luaScript.Globals["magnitude"] = (Func<float, float, float>)CalculateMagnitude;
        luaScript.Globals["time"] = (Func<float>)GetTime;

        // Marshaling examples
        List<int> numbers = new List<int> { 3, 4, 1, 2, 5 };
        luaScript.Globals["numbers"] = numbers;

        Dictionary<string, string> dict = new Dictionary<string, string>
        {
            { "first_name", "John" },
            { "last_name", "Doe" }
        };
        luaScript.Globals["dict"] = dict;

        Dictionary<string, object> binaryTree = MakeSimpleTree();
        luaScript.Globals["binaryTree"] = binaryTree;

        string lua_code = @"
            -- Called from C# script 
            function update()
                local currentTime = time()  -- Get time from C# script
                print('Time since startup: ' .. currentTime)
            end

            x = 3
            y = 4
            z = magnitude(x, y)
            print('z = ' .. z)

            -- Print List
            for i, num in ipairs(numbers) do print('list- i: ' .. i .. ' value: ' .. num) end

            -- Print Dictionary
            for key, value in pairs(dict) do print('dict- ' .. key .. ': ' .. value) end

            -- Print Binary Tree
            function printTree(tree)
                if tree == nil then return end
                print('binary tree traverse: ' .. tree.value)
                printTree(tree.left)
                printTree(tree.right)
            end

            printTree(binaryTree)
        ";

        try
        {
            luaScript.DoString(lua_code);
        }
        catch (ScriptRuntimeException e)
        {
            Debug.LogError("Lua error: " + e.DecoratedMessage);
        }

        // Register callable functions. 
        luaUpdateFunction = luaScript.Globals.Get("update");

        DynValue xValue = luaScript.Globals.Get("x");
        Debug.Log("Getting variable x from state: " + xValue.Number);
        CallLuaUpdate();
    }

    private static Dictionary<string, object> MakeSimpleTree()
    {
        return new Dictionary<string, object>
        {
            { "value", 10 },
            { "left", new Dictionary<string, object>
                {
                    { "value", 5 },
                    { "left", null },
                    { "right", null }
                }
            },
            { "right", new Dictionary<string, object>
                {
                    { "value", 20 },
                    { "left", null },
                    { "right", null }
                }
            }
        };
    }

    void Update()
    {
        //CallLuaUpdate();
    }

    private void CallLuaUpdate()
    {
        // Safely call the Lua update function if it exists
        if (luaUpdateFunction.Type == DataType.Function)
        {
            luaScript.Call(luaUpdateFunction);
        }
    }

    static public void LuaPrint(string message)
    {
        Debug.Log(message);
    }

    static public float CalculateMagnitude(float x, float y)
    {
        return (float)Math.Sqrt(x * x + y * y);
    }

    static public float GetTime()
    {
        return (float)Time.realtimeSinceStartup;
    }

    [UnityEditor.Callbacks.DidReloadScripts]
    static void CreateBindings()
    {
        string pathToLuaDirectory = "U:/GitHub/MoonSharp - Unity - Example/Assets/Scripts";

        //Find all types marked wieht MoonSharpUserData attribute
        List<Type> luaProxyTypes = VizplayLuaManager.GetMoonSharpTypes(typeof(LuaTutorial).Assembly);

        //Compile a lua bindings file
        string finalLuaFileStr = "--Warning: Don't Mess With This!!!\nThis File Has Been Autogenerated by Dan 'Golden Boy' Hope\n";

        //add Legend to give user a hint on the layout used
        finalLuaFileStr += "\nLayout below shows Script Name and then C# commands available that have Lua bindings\n e.g. [C# Mehtod Name] = function(param name <param Type>)\n";

        foreach (Type t in luaProxyTypes)
        {
            string shortenedTypeName = t.Name;

            //if (t.Name.Contains("LuaProxy"))
            //{
            //    shortenedTypeName = shortenedTypeName.Remove(t.Name.Length - 8, 8);
            //}

            //make it look nice
            finalLuaFileStr += "\n*****************************";

            //global obj
            finalLuaFileStr += ("\n" + shortenedTypeName + "\n");

            //make it look nice
            finalLuaFileStr += "*****************************\n";

            //functions
            MethodInfo[] methods = t.GetMethods();

            foreach (MethodInfo m in methods)
            {
                if (!m.IsPublic)
                {
                    continue;
                }
                if (m.DeclaringType != t)
                {
                    continue;
                }

                finalLuaFileStr += m.Name + " = function(";

                //get params
                int length = m.GetParameters().Length;
                int i = 0;

                foreach (ParameterInfo p in m.GetParameters())
                {
                    
                    if (i < length - 1)
                    {
                        finalLuaFileStr += p.Name + " <" + p.ParameterType.Name + ">, ";
                    }
                    else
                    {
                        finalLuaFileStr += p.Name + " <" + p.ParameterType.Name + ">";
                    }
                    i++;
                }
                
                finalLuaFileStr += ")end\n";
            }
        }

        File.WriteAllText(Application.persistentDataPath + "/_bindings_autogen.lua", finalLuaFileStr);
        Debug.Log("Lua bindings have been generated");
    }
}
